version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: npm install
          command: npm install

      - run:
          name: Bootstrap
          command: $(npm bin)/lerna bootstrap

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: test
          command: npm test
