version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.11.1

      # Service container image available at `host: localhost`
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: steps_admin_test

      - image: cypress/base:6
        environment:
          TERM: xterm

    environment:
      NODE_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          key: v1-api-dependencies-{{ checksum "apps/api/package.json" }}
      - restore_cache:
          key: v1-admin-dependencies-{{ checksum "apps/admin/package.json" }}

      - run:
          name: Install additional dependencies
          command: |
            sudo apt-get install --yes --quiet \
              libgtk2.0-0 \
              libnotify-dev \
              libgconf-2-4 \
              libnss3 \
              libxss1 \
              libasound2 \
              xvfb \
              sqitch \
              libdbd-pg-perl \
              postgresql-client

      - run:
          name: npm install
          command: npm install

      - run:
          name: npm install:all
          command: npm run install:all

      - run:
          name: Database migrations
          command: |
            sqitch deploy --target pg://postgres@localhost/steps_admin_test

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/repo/node_modules

      - save_cache:
          key: v1-api-dependencies-{{ checksum "apps/api/package.json" }}
          paths:
            - ~/repo/apps/api/node_modules

      - save_cache:
          key: v1-admin-dependencies-{{ checksum "apps/admin/package.json" }}
          paths:
            - ~/repo/apps/admin/node_modules

      - run:
          name: "Test: Admin"
          command: $(npm bin)/lerna exec -- npm test --scope=steps-admin

      - run:
          name: "Test: Api"
          command: $(npm bin)/lerna exec -- npm test --scope=steps-api

      # - run:
      #     name: cypress
      #     command: |
      #       $(npm bin)/cypress install
      #       $(npm bin)/cypress run

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
