version: 2
jobs:
  build:
    docker:
      - image: itsthatguy/docker-cypress-sqitch:latest
        environment:
          TERM: xterm

      # Service container image available at `host: localhost`
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: steps_admin_test

    environment:
      NODE_ENV: test

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: v1-api-dependencies-{{ checksum "apps/api/package-lock.json" }}
      - restore_cache:
          key: v1-admin-dependencies-{{ checksum "apps/admin/package-lock.json" }}

      - run:
          name: npm install
          command: npm install

      - run:
          name: npm install:all
          command: npm run install:all

      - run:
          name: Database migrations
          command: |
            sqitch deploy --target pg://postgres@localhost/steps_admin_test

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/repo/node_modules

      - save_cache:
          key: v1-api-dependencies-{{ checksum "apps/api/package-lock.json" }}
          paths:
            - ~/repo/apps/api/node_modules

      - save_cache:
          key: v1-admin-dependencies-{{ checksum "apps/admin/package-lock.json" }}
          paths:
            - ~/repo/apps/admin/node_modules

      - run:
          name: test
          command: npm test

      # - run:
      #     name: cypress
      #     command: |
      #       $(npm bin)/cypress install
      #       $(npm bin)/cypress run

      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots
